#!/usr/bin/env bash

set -e # Exit on error
set -o xtrace # Trace commands

# The --build-file flag doesn't keep the same project root.
# So we need to copy the build file to the solvents root.
cp lang/java/build.gradle .

gradle check --info
