#!/usr/bin/env bash 

set -e # Exit on error

# TODO(b0ri5): Make a common script for finding relevant files.
for file in $(find . \
    -name '*.h' -not -path './third_party/*' && \
    find . -name '*.cc' -not -path './third_party/*')
do
  echo "Running clang-format on ${file}"
  clang-format-3.5 -i --style=Google ${file}
done
