#!/usr/bin/env bash

# Install clang-format and modernize
sudo apt-get install clang-format-3.5 clang-modernize-3.5

# Install gtest
mkdir -p third_party
cd third_party
wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
unzip -o -q gtest-1.7.0.zip
cd gtest-1.7.0
cmake \
  -DCMAKE_CXX_FLAGS="-std=c++11" \
  .
cmake --build .
