#!/usr/bin/env bash

mkdir -p third_party
cd third_party
wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
unzip -o -q gtest-1.7.0.zip
cd gtest-1.7.0
cmake \
  -DCMAKE_CXX_COMPILER="clang++" \
  -DCMAKE_CXX_FLAGS="-std=c++11" \
  .
cmake --build .
