#!/usr/bin/env bash

set -e # Exit on error

EXIT_CODE=0
for file in $(find . -name '*.cc' -or -name '*.h' -not -path './third_party/*')
do
  DIFF=$(clang-format-3.5 --style=Google ${file} | diff - ${file})
  if [[ ${DIFF} ]]; then
    echo "${DIFF}"
    EXIT_CODE=1
  fi
done

exit ${EXIT_CODE}
