#!/usr/bin/env bash

set -e # Exit on error
set -o xtrace

EXIT_CODE=0
# TODO(b0ri5): Make a common script for finding relevant files.
for file in $(find . \
    -name '*.h' -not -path './third_party/*' && \
    find . -name '*.cc' -not -path './third_party/*')
do
  echo "Diffing ${file} with clang-format"
  DIFF=$(clang-format-3.5 --style=Google ${file} | diff - ${file})
  if [[ ${DIFF} ]]; then
    echo "${DIFF}"
    EXIT_CODE=1
  fi
done

exit ${EXIT_CODE}
