#!/usr/bin/env bash

set -e # Exit on error

sudo apt-get install python3.3
sudo pip install virtualenv
virtualenv --version
virtualenv --python=python3.3 ~/virtualenv/python3.3
source ~/virtualenv/python3.3/bin/activate
python --version
pip install nose
nosetests --version
pip install pylint
pylint --version
