#!/usr/bin/env python

import os
import shutil

def main():
  for root, dirs, files in os.walk('.'):
    if root.startswith('./.') or \
       root.startswith('./build') or \
       root.startswith('./lang') or \
       root.startswith('./third_party') or \
       root.startswith('./dist') or \
       '__pycache__' in root or \
       root == '.':
      continue
    for file in files:
      if file.endswith('.hs'):
        dest_dir = os.path.join('lang/hs/src', capitalize_dirs(root))
        if not os.path.exists(dest_dir):
          os.makedirs(dest_dir)
          print('os.makedirs(' + dest_dir + ')')
        src = os.path.join(root, file)
        dest = os.path.join(dest_dir, file)
        shutil.copyfile(src, dest)
        print('shutil.copyfile(%s, %s)' % (src, dest))

def capitalize_dirs(dir):
  dir = os.path.normpath(dir)
  dirs = []
  while True:
    head, tail = os.path.split(dir)
    dirs = [tail[0].upper() + tail[1:]] + dirs
    if not head:
      break
    dir = head
  return os.path.join(*dirs)
  
if __name__ == '__main__':
  main()
