#!/usr/bin/env bash

set -e # Exit on error

HS_FILES=""
for file in $(find . -name '*.hs')
do
  if [[ ${file} == ./lang* ||
        ${file} == ./build* ]]
  then
    continue
  fi 

  HS_FILES="${HS_FILES} ${file}"
done

hlint $HS_FILES
