#!/usr/bin/env bash

set -e # Exit on error

# See http://godoc.org/code.google.com/p/go.tools/cmd/vet
# Exits with code 1 on error
go tool vet -v .

# gofmt always exits with 0
DIFF=$(gofmt -d -s .)
if [[ ${DIFF} ]]; then
  echo "${DIFF}"
  exit 1
fi
