#!/usr/bin/env bash

set -o xtrace

echo "Building Go!"

# All go files must be in the src/ subdirectory:
#  http://golang.org/doc/code.html#Organization
rsync -a --include='*.go' --exclude='src/' --include='*/' --exclude='*' -v --prune-empty-dirs . src

go test -v ./src/...

exit 0
